project:
  type: book

book:
  title: "Technical Communication for the Social, Behavioral, and Management Sciences"
  author: 
    - name: John Kulas
      email: jtkulas@ergreports.com
      degrees: PhD
      affiliations:
        - name: TBD
  date: "January 2025"
  sharing: [twitter, facebook]
  twitter-card: true
  repo-url: https://github.com/jtkulas/SBMAuthoring
  repo-actions: [edit, issue]
#  downloads: pdf
  favicon: https://datavizcatalogue.com/methods/images/top_images/SVG/density_plot.svg
  cover-image: https://datavizcatalogue.com/methods/images/top_images/SVG/density_plot.svg
  navbar: 
    logo: https://datavizcatalogue.com/methods/images/top_images/SVG/density_plot.svg
  page-footer: 
    right: |
      Current resource authored via <a href="https://quarto.org/docs/books/">Quarto</a>.
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd           
    - platforms.qmd
    - references.qmd
  appendices: 
    - history.qmd
    - resources.qmd
    - quotes.qmd

custom-callout:               ## https://quarto.thecoatlessprofessor.com/custom-callout/
  definition:
    title: "Definition"
    icon-symbol: "📜"
    color: "#C1AA98"
bibliography: references.bib

format:
  html:
    toc-title: On this page
    code-annotations: hover
    theme: 
      light: flatly
      dark: darkly
    crossref: 
      custom:
        - kind: float
          reference-prefix: Video
          key: vid
#  pdf: default                                 ## `knitr:::webshot_available()`
#    documentclass: scrreprt   
#      cover-image: https://cdn.pixabay.com/photo/2016/08/02/18/27/statistic-1564428_1280.png
engine: knitr
filters: 
  - custom-callout
comments: 
  hypothesis: true
