project:
  type: book

book:
  title: "Psychometrics"
  author: "Pink Panther, esq."
  date: "3/25/2024"
  sharing: [twitter, facebook]
  twitter-card: true
  repo-url: https://github.com/jtkulas/bookexample
  repo-actions: [edit, issue]
  downloads: pdf
  favicon: https://datavizcatalogue.com/methods/images/top_images/SVG/density_plot.svg
  cover-image: https://cdn.pixabay.com/photo/2016/08/02/18/27/statistic-1564428_1280.png
  navbar: 
    logo: https://datavizcatalogue.com/methods/images/top_images/SVG/density_plot.svg
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc-title: On this page
    code-annotations: hover
    theme: 
      light: flatly
      dark: darkly
  pdf:                                 ## `knitr:::webshot_available()`
    documentclass: scrreprt   
    cover-image: https://cdn.pixabay.com/photo/2016/08/02/18/27/statistic-1564428_1280.png

comments: 
  hypothesis: true
