project:
  type: book

book:
  title: "Literate programming for the Social, Behavioral, and Management sciences"
  author: 
    - name: John Kulas
      email: jtkulas@ergreports.com
      degrees: PhD
      affiliations:
        - name: TBD
  date: "January 2025"
  sharing: [twitter, facebook]
  twitter-card: true
  repo-url: https://github.com/jtkulas/SBMAuthoring
  repo-actions: [edit, issue]
#  downloads: pdf
  favicon: https://datavizcatalogue.com/methods/images/top_images/SVG/density_plot.svg
  cover-image: https://datavizcatalogue.com/methods/images/top_images/SVG/density_plot.svg
  navbar: 
    logo: https://datavizcatalogue.com/methods/images/top_images/SVG/density_plot.svg
  page-footer: 
    right: |
      Current resource authored via <a href="https://quarto.org/docs/books/">Quarto</a>.
  chapters:
    - index.qmd
    - summary.qmd            ## types of output first, then code reveal next
    - intro.qmd
    - platforms.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc-title: On this page
    code-annotations: hover
    theme: 
      light: flatly
      dark: darkly
#  pdf: default                                 ## `knitr:::webshot_available()`
#   documentclass: scrreprt   
#    cover-image: https://cdn.pixabay.com/photo/2016/08/02/18/27/statistic-1564428_1280.png
engine: knitr
comments: 
  hypothesis: true
